"""Repository interfaces.

Two implementations: `memory` (dev/tests, zero credentials) and `firestore`
(production). Routers depend only on these protocols.
"""
from __future__ import annotations

from typing import Optional, Protocol

from ..models import Booking, Listing, Message, Report, Review, UserProfile


class UserRepo(Protocol):
    def get(self, uid: str) -> Optional[UserProfile]: ...
    def upsert(self, user: UserProfile) -> UserProfile: ...


class ListingRepo(Protocol):
    def get(self, listing_id: str) -> Optional[Listing]: ...
    def create(self, listing: Listing) -> Listing: ...
    def update(self, listing: Listing) -> Listing: ...
    def by_owner(self, owner_uid: str) -> list[Listing]: ...
    def by_geohash_prefixes(self, prefixes: list[str], limit: int = 200) -> list[Listing]: ...
    def get_exact_address(self, listing_id: str) -> str: ...
    def set_exact_address(self, listing_id: str, address: str) -> None: ...


class BookingRepo(Protocol):
    def get(self, booking_id: str) -> Optional[Booking]: ...
    def create(self, booking: Booking) -> Booking: ...
    def update(self, booking: Booking) -> Booking: ...
    def for_user(self, uid: str) -> list[Booking]: ...
    def by_listing(self, listing_id: str) -> list[Booking]: ...
    def overlapping(self, listing_id: str, start, end) -> list[Booking]: ...


class MessageRepo(Protocol):
    def create(self, message: Message) -> Message: ...
    def for_booking(self, booking_id: str, limit: int = 100) -> list[Message]: ...


class ReviewRepo(Protocol):
    def create(self, review: Review) -> Review: ...
    def for_user(self, uid: str) -> list[Review]: ...
    def for_booking_from(self, booking_id: str, from_uid: str) -> Optional[Review]: ...


class ReportRepo(Protocol):
    def create(self, report: Report) -> Report: ...
